module Form where

import Text.Printf
import Modifier
import Race
import Character
import Skill
import Ability
import Power
import Feat
import Pontus


printFormData = do
  putStrLn "$fields = {"
  printf "  'Player name' => q{%s},\n" "Eric Wollesen"
  printf "  'Character name' => q{%s},\n" $ Character.name pontus
  printf "  'Level' => q{%d},\n" $ Character.level pontus
  printf "  'Class' => q{%s},\n" $ Character.className pontus
  printf "  'Paragon path' => q{%s},\n" "NS"
  printf "  'Epic destiny' => q{%s},\n" "NS"
  printf "  'Total XP' => q{%d},\n" $ Character.xp pontus
  printf "  'Race' => q{%s},\n" $ (Race.name . Character.race) pontus
  printf "  'Size' => q{%s},\n" $ (Race.size . Character.race) pontus
  printf "  'Age' => q{%d},\n" $ Character.age pontus
  printf "  'Gender' => q{%s},\n" $ Character.gender pontus
  printf "  'Height' => q{%s},\n" $ Character.height pontus
  printf "  'Weight' => q{%s},\n" $ Character.weight pontus
  printf "  'Alignment' => q{%s},\n" $ Character.alignment pontus
  printf "  'Deity' => q{%s},\n" $ Character.deity pontus
  printf "  'Adventuring company or other affiliation' => q{%s},\n" "NS"
  printf "  'Dex mod to Init' => q{%+d},\n" $ Character.dexMod pontus
  printf "  'Half-level mod to Init' => q{%+d},\n" $ Character.halfLevel pontus
  printf "  'Misc. mod to Init' => q{%s},\n" "NS"
  printf "  'Init' => q{%+d},\n" $ Character.initiative pontus
  printf "  'Conditional Init mods' => q{%s},\n" "NS"
  printf "  'Ten plus half-level mod to AC' => q{%+d},\n" $ Character.tenPlusHalfLevel pontus
  printf "  'Armor or ability mod to AC' => q{%+d},\n" $ Character.armorOrAbilityModToAC pontus
  printf "  'Class mod to AC' => q{%+d},\n" $ Character.classModToAC pontus
  printf "  'Feat mod to AC' => q{%+d},\n" $ Character.featModToAC pontus
  printf "  'Enhancement mod to AC' => q{%s},\n" "NS"
  printf "  'Misc. mod 1 to AC' => q{%s},\n" "NS"
  printf "  'Misc. mod 2 to AC' => q{%s},\n" "NS"
  printf "  'AC' => q{%d},\n" $ Character.ac pontus
  printf "  'Ten plus half-level to Fortitude' => q{%+d},\n" $ Character.tenPlusHalfLevel pontus
  printf "  'Ability mod to Fortitude' => q{%+d},\n" $ Character.abilityModToFortitude pontus
  printf "  'Class mod to Fortitude' => q{%+d},\n" $ Character.classModToFortitude pontus
  printf "  'Feat mod to Fortitude' => q{%+d},\n" $ Character.featModToFortitude pontus
  printf "  'Enhancement mod to Fortitude' => q{%s},\n" "NS"
  printf "  'Misc. mod 1 to Fortitude' => q{%s},\n" "NS"
  printf "  'Misc. mod 2 to Fortitude' => q{%s},\n" "NS"
  printf "  'Fortitude' => q{%d},\n" $ Character.fortitude pontus
  printf "  'Ten plus half-level to Reflex' => q{%+d},\n" $ Character.tenPlusHalfLevel pontus
  printf "  'Ability mod to Reflex' => q{%+d},\n" $ Character.abilityModToReflex pontus
  printf "  'Class mod to Reflex' => q{%+d},\n" $ Character.classModToReflex pontus
  printf "  'Feat mod to Reflex' => q{%+d},\n" $ Character.featModToReflex pontus
  printf "  'Enhancement mod to Reflex' => q{%s},\n" "NS"
  printf "  'Misc. mod 1 to Reflex' => q{%s},\n" "NS"
  printf "  'Misc. mod 2 to Reflex' => q{%s},\n" "NS"
  printf "  'Reflex' => q{%d},\n" $ Character.reflex pontus
  printf "  'Ten plus half-level to Will' => q{%+d},\n" $ Character.tenPlusHalfLevel pontus
  printf "  'Ability mod to Will' => q{%+d},\n" $ Character.abilityModToWill pontus
  printf "  'Class mod to Will' => q{%+d},\n" $ Character.classModToWill pontus
  printf "  'Feat mod to Will' => q{%+d},\n" $ Character.featModToWill pontus
  printf "  'Enhancement mod to Will' => q{%s},\n" "NS"
  printf "  'Misc. mod 1 to Will' => q{%s},\n" "NS"
  printf "  'Misc. mod 2 to Will' => q{%s},\n" "NS"
  printf "  'Will' => q{%d},\n" $ Character.will pontus
  printf "  'Attack workspace ability 1' => q{%s},\n" "NS"
  printf "  'Attack workspace ability 2' => q{%s},\n" "NS"
  printf "  'Additional effects to spending action points' => q{%s},\n" "NS"
  printf "  'Conditional mods to AC' => q{%s},\n" "NS"
  printf "  'Conditional mods to Fortitude' => q{%s},\n" "NS"
  printf "  'Conditional mods to Reflex' => q{%s},\n" "NS"
  printf "  'Conditional mods to Will' => q{%s},\n" "NS"
  printf "  'Race features - Ability score mods' => q{%s},\n" "NS"
  printf "  'Race features line 2' => q{%s},\n" ""
  printf "  'Race features line 3' => q{%s},\n" ""
  printf "  'Race features line 4' => q{%s},\n" ""
  printf "  'Race features line 5' => q{%s},\n" ""
  printf "  'Race features line 6' => q{%s},\n" ""
  printf "  'Race features line 7' => q{%s},\n" ""
  printf "  'Race features line 8' => q{%s},\n" ""
  printf "  'Race features line 9' => q{%s},\n" ""
  printf "  'Str' => q{%d},\n" $ Character.str pontus
  printf "  'Ability mod from Str' => q{%+d},\n" $ Character.strMod pontus
  printf "  'Str mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.strMod pontus
  printf "  'Con' => q{%d},\n" $ Character.con pontus
  printf "  'Ability mod from Con' => q{%+d},\n" $ Character.conMod pontus
  printf "  'Con mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.conMod pontus
  printf "  'Dex' => q{%d},\n" $ Character.dex pontus
  printf "  'Ability mod from Dex' => q{%+d},\n" $ Character.dexMod pontus
  printf "  'Dex mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.dexMod pontus
  printf "  'Int' => q{%d},\n" $ Character.int pontus
  printf "  'Ability mod to Int' => q{%+d},\n" $ Character.intMod pontus
  printf "  'Int mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.intMod pontus
  printf "  'Wis' => q{%d},\n" $ Character.wis pontus
  printf "  'Ability mod from Wis' => q{%+d},\n" $ Character.wisMod pontus
  printf "  'Wis mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.wisMod pontus
  printf "  'Cha' => q{%d},\n" $ Character.cha pontus
  printf "  'Ability mod from Cha' => q{%+d},\n" $ Character.chaMod pontus
  printf "  'Cha mod w/ level' => q{%+d},\n" $ Character.halfLevel pontus + Character.chaMod pontus
  printf "  'Speed' => q{%d},\n" $ Character.speed pontus
  printf "  'Base Speed' => q{%d},\n" $ (Race.baseSpeed . Character.race) pontus
  printf "  'Armor Speed mod' => q{%+d},\n" $ Character.armorSpeedMod pontus
  printf "  'Item Speed mod' => q{%s},\n" "NS"
  printf "  'Misc. Speed mod' => q{%s},\n" "NS"
  printf "  'Special movement' => q{%s},\n" "NS"
  printf "  'Trained in Acrobatics' => q{%d},\n" $ trainedBonus pontus Acrobatics
  printf "  'Trained in Arcana' => q{%d},\n" $ trainedBonus pontus Arcana
  printf "  'Trained in Athletics' => q{%d},\n" $ trainedBonus pontus Athletics
  printf "  'Trained in Bluff' => q{%d},\n" $ trainedBonus pontus Bluff
  printf "  'Trained in Diplomacy' => q{%d},\n" $ trainedBonus pontus Diplomacy
  printf "  'Trained in Dungeoneering' => q{%d},\n" $ trainedBonus pontus Dungeoneering
  printf "  'Trained in Endurance' => q{%d},\n" $ trainedBonus pontus Endurance
  printf "  'Trained in Heal' => q{%d},\n" $ trainedBonus pontus Heal
  printf "  'Trained in History' => q{%d},\n" $ trainedBonus pontus History
  printf "  'Trained in Insight' => q{%d},\n" $ trainedBonus pontus Insight
  printf "  'Trained in Intimidate' => q{%d},\n" $ trainedBonus pontus Intimidate
  printf "  'Trained in Nature' => q{%d},\n" $ trainedBonus pontus Nature
  printf "  'Trained in Perception' => q{%d},\n" $ trainedBonus pontus Perception
  printf "  'Trained in Religion' => q{%d},\n" $ trainedBonus pontus Religion
  printf "  'Trained in Stealth' => q{%d},\n" $ trainedBonus pontus Stealth
  printf "  'Trained in Streetwise' => q{%d},\n" $ trainedBonus pontus Streetwise
  printf "  'Trained in Thievery' => q{%d},\n" $ trainedBonus pontus Thievery
  printf "  'Ability mod plus half-level to Acrobatics' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Acrobatics
  printf "  'Armor mod to Acrobatics' => q{%+d},\n" $ skillArmorCheckPenalty pontus Acrobatics
  printf "  'Misc. mod to Acrobatics' => q{%s},\n" "NS"
  printf "  'Acrobatics' => q{%+d},\n" $ skill pontus Acrobatics
  printf "  'Passive Insight' => q{%d},\n" $ passiveInsight pontus
  printf "  'Passive Insight skill mod' => q{%+d},\n" $ skill pontus Insight
  printf "  'Passive Perception' => q{%d},\n" $ passivePerception pontus
  printf "  'Passive Perception skill mod' => q{%+d},\n" $ skill pontus Perception
  printf "  'Special senses' => q{%s},\n" "NS"
  printf "  'Max HP' => q{%d},\n" $ Character.hp pontus
  printf "  'Bloodied' => q{%d},\n" $ Character.bloodied pontus
  printf "  'Surge value' => q{%d},\n" $ Character.healingSurgeValue pontus
  printf "  'Surges per day' => q{%d},\n" $ Character.healingSurgesPerDay pontus
  printf "  'Saving throw mods' => q{%s},\n" "NS"
  printf "  'Resistances' => q{%s},\n" "NS"
  printf "  'Current conditions and effects' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 1' => q{%s},\n" "NS"
  printf "  'Class, Path, or Destiny features line 2' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 3' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 4' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 5' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 6' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 7' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 8' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 9' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 10' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 11' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 12' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 13' => q{%s},\n" ""
  printf "  'Class, Path, or Destiny features line 14' => q{%s},\n" ""
  printf "  'Languages known line 1' => q{%s},\n" $ firstLanguage pontus
  printf "  'Languages known line 2' => q{%s},\n" $ secondLanguage pontus
  printf "  'Languages known line 3' => q{%s},\n" $ thirdLanguage pontus
  printf "  'Misc. mod to Arcana' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Arcana' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Arcana
  printf "  'Arcana' => q{%+d},\n" $ skill pontus Arcana
  printf "  'Ability mod plus half-level to Athletics' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Athletics
  printf "  'Armor mod to Athletics' => q{%+d},\n" $ skillArmorCheckPenalty pontus Athletics
  printf "  'Misc. mod to Athletics' => q{%s},\n" "NS"
  printf "  'Athletics' => q{%+d},\n" $ skill pontus Athletics
  printf "  'Ability mod plus half-level to Bluff' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Bluff
  printf "  'Misc. mod to Bluff' => q{%s},\n" "NS"
  printf "  'Bluff' => q{%+d},\n" $ skill pontus Bluff
  printf "  'Ability mod plus half-level to Diplomacy' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Diplomacy
  printf "  'Misc. mod to Diplomacy' => q{%s},\n" "NS"
  printf "  'Diplomacy' => q{%+d},\n" $ skill pontus Diplomacy
  printf "  'Ability mod plus half-level to Dungeoneering' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Dungeoneering
  printf "  'Misc. mod to Dungeoneering' => q{%s},\n" "NS"
  printf "  'Dungeoneering' => q{%+d},\n" $ skill pontus Dungeoneering
  printf "  'Armor mod to Endurance' => q{%+d},\n" $ skillArmorCheckPenalty pontus Endurance
  printf "  'Misc. mod to Endurance' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Endurance' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Endurance
  printf "  'Endurance' => q{%+d},\n" $ skill pontus Endurance
  printf "  'Ability mod plus half-level to Heal' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Heal
  printf "  'Misc. mod to Heal' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to History' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus History
  printf "  'Heal' => q{%+d},\n" $ skill pontus Heal
  printf "  'Misc. mod to History' => q{%s},\n" "NS"
  printf "  'History' => q{%+d},\n" $ skill pontus History
  printf "  'Insight' => q{%+d},\n" $ skill pontus Insight
  printf "  'Misc. mod to Insight' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Insight' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Insight
  printf "  'Intimidate' => q{%+d},\n" $ skill pontus Intimidate
  printf "  'Misc. mod to Intimidate' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Intimidate' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Intimidate
  printf "  'Nature' => q{%+d},\n" $ skill pontus Nature
  printf "  'Misc. mod to Nature' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Nature' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Nature
  printf "  'Perception' => q{%+d},\n" $ skill pontus Perception
  printf "  'Misc. mod to Perception' => q{%s},\n" "NS"
  printf "  'Misc. mod to Religion' => q{%s},\n" "NS"
  printf "  'Religion' => q{%+d},\n" $ skill pontus Religion
  printf "  'Ability mod plus half-level to Perception' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Perception
  printf "  'Ability mod plus half-level to Religion' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Religion
  printf "  'Stealth' => q{%+d},\n" $ skill pontus Stealth
  printf "  'Armor mod to Stealth' => q{%+d},\n" $ skillArmorCheckPenalty pontus Stealth
  printf "  'Misc. mod to Stealth' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Stealth' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Stealth
  printf "  'Streetwise' => q{%+d},\n" $ skill pontus Streetwise
  printf "  'Misc. mod to Streetwise' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Streetwise' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Streetwise
  printf "  'Thievery' => q{%+d},\n" $ skill pontus Thievery
  printf "  'Armor mod to Thievery' => q{%+d},\n" $ skillArmorCheckPenalty pontus Thievery
  printf "  'Misc. mod to Thievery' => q{%s},\n" "NS"
  printf "  'Ability mod plus half-level to Thievery' => q{%+d},\n" $ skillAbilModPlusHalfLevel pontus Thievery
  printf "  'Attack mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Half-level to attack 1' => q{%+d},\n" $ halfLevel pontus
  printf "  'Ability mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Class mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Proficiency mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Feat mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Enhancement mod to attack 1' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod to attack 1' => q{%s},\n" "NS"
  printf "  'Attack mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Half-level to attack 2' => q{%+d},\n" $ halfLevel pontus
  printf "  'Ability mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Class mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Proficiency mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Feat mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Enhancement mod to attack 2' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod to attack 2' => q{%s},\n" "NS"
  printf "  'Damage workspace ability 1' => q{%s},\n" ""
  printf "  'Damage workspace ability 2' => q{%s},\n" ""
  printf "  'Damage to ability 1' => q{%s},\n" ""
  printf "  'Ability mod to damage to ability 1' => q{%+d},\n" (0 :: Int)
  printf "  'Feat mod to damage to ability 1' => q{%+d},\n" (0 :: Int)
  printf "  'Enhancement mod to damage to ability 1' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod 1 to damage to ability 1' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod 2 to damage to ability 1' => q{%+d},\n" (0 :: Int)
  printf "  'Damage to ability 2' => q{%s},\n" ""
  printf "  'Ability mod to damage to ability 2' => q{%+d},\n" (0 :: Int)
  printf "  'Feat mod to damage to ability 2' => q{%+d},\n" (0 :: Int)
  printf "  'Enhancement mod to damage to ability 2' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod 1 to damage to ability 2' => q{%+d},\n" (0 :: Int)
  printf "  'Misc. mod 2 to damage to ability 2' => q{%+d},\n" (0 :: Int)
  printf "  'Basic attack 1 attack' => q{%+d},\n" (0 :: Int)
  printf "  'Basic attack 1 defense' => q{%s},\n" ""
  printf "  'Basic attack 2 attack' => q{%s},\n" ""
  printf "  'Basic attack 2 defense' => q{%s},\n" ""
  printf "  'Basic attack 3 attack ' => q{%s},\n" ""
  printf "  'Basic attack 3 defense' => q{%s},\n" ""
  printf "  'Basic attack 4 attack ' => q{%s},\n" ""
  printf "  'Basic attack 4 defense' => q{%s},\n" ""
  printf "  'Basic attack 1 weapon or power' => q{%s},\n" ""
  printf "  'Basic attack 2 weapon or power' => q{%s},\n" ""
  printf "  'Basic attack 3 weapon or power' => q{%s},\n" ""
  printf "  'Basic attack 4 weapon or power' => q{%s},\n" ""
  printf "  'Basic attack 1 damage' => q{%s},\n" ""
  printf "  'Basic attack 2 damage' => q{%s},\n" ""
  printf "  'Basic attack 3 damage' => q{%s},\n" ""
  printf "  'Basic attack 4 damage' => q{%s},\n" ""
  -- iterate over me somehow
  printf "  'Feats line 1' => q{%s},\n" $ (seventeenFeats pontus) !! 0
  printf "  'Feats line 2' => q{%s},\n" $ (seventeenFeats pontus) !! 1
  printf "  'Feats line 3' => q{%s},\n" $ (seventeenFeats pontus) !! 2
  printf "  'Feats line 4' => q{%s},\n" $ (seventeenFeats pontus) !! 3
  printf "  'Feats line 5' => q{%s},\n" $ (seventeenFeats pontus) !! 4
  printf "  'Feats line 6' => q{%s},\n" $ (seventeenFeats pontus) !! 5
  printf "  'Feats line 7' => q{%s},\n" $ (seventeenFeats pontus) !! 6
  printf "  'Feats line 8' => q{%s},\n" $ (seventeenFeats pontus) !! 7
  printf "  'Feats line 9' => q{%s},\n" $ (seventeenFeats pontus) !! 8
  printf "  'Feats line 10' => q{%s},\n" $ (seventeenFeats pontus) !! 9
  printf "  'Feats line 11' => q{%s},\n" $ (seventeenFeats pontus) !! 10
  printf "  'Feats line 12' => q{%s},\n" $ (seventeenFeats pontus) !! 11
  printf "  'Feats line 13' => q{%s},\n" $ (seventeenFeats pontus) !! 12
  printf "  'Feats line 14' => q{%s},\n" $ (seventeenFeats pontus) !! 13
  printf "  'Feats line 15' => q{%s},\n" $ (seventeenFeats pontus) !! 14
  printf "  'Feats line 16' => q{%s},\n" $ (seventeenFeats pontus) !! 15
  printf "  'Feats line 17' => q{%s},\n" $ (seventeenFeats pontus) !! 16
  printf "  'At-will powers line 1' => q{%s},\n" $ (sixAtWillPowers pontus) !! 0
  printf "  'At-will powers line 2' => q{%s},\n" $ (sixAtWillPowers pontus) !! 1
  printf "  'At-will powers line 3' => q{%s},\n" $ (sixAtWillPowers pontus) !! 2
  printf "  'At-will powers line 4' => q{%s},\n" $ (sixAtWillPowers pontus) !! 3
  printf "  'At-will powers line 5' => q{%s},\n" $ (sixAtWillPowers pontus) !! 4
  printf "  'At-will powers line 6' => q{%s},\n" $ (sixAtWillPowers pontus) !! 5
  printf "  'Daily powers line 1' => q{%s},\n" $ (sixDailyPowers pontus) !! 0
  printf "  'Daily powers line 2' => q{%s},\n" $ (sixDailyPowers pontus) !! 1
  printf "  'Daily powers line 3' => q{%s},\n" $ (sixDailyPowers pontus) !! 2
  printf "  'Daily powers line 4' => q{%s},\n" $ (sixDailyPowers pontus) !! 3
  printf "  'Daily powers line 5' => q{%s},\n" $ (sixDailyPowers pontus) !! 4
  printf "  'Daily powers line 6' => q{%s},\n" $ (sixDailyPowers pontus) !! 5
  printf "  'Encounter powers line 1' => q{%s},\n" $ (sixEncounterPowers pontus) !! 0
  printf "  'Encounter powers line 6' => q{%s},\n" $ (sixEncounterPowers pontus) !! 1
  printf "  'Encounter powers line 2' => q{%s},\n" $ (sixEncounterPowers pontus) !! 2
  printf "  'Encounter powers line 3' => q{%s},\n" $ (sixEncounterPowers pontus) !! 3
  printf "  'Encounter powers line 4' => q{%s},\n" $ (sixEncounterPowers pontus) !! 4
  printf "  'Encounter powers line 5' => q{%s},\n" $ (sixEncounterPowers pontus) !! 5
  printf "  'Utility powers line 1' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 0
  printf "  'Utility powers line 2' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 1
  printf "  'Utility powers line 3' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 2
  printf "  'Utility powers line 4' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 3
  printf "  'Utility powers line 5' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 4
  printf "  'Utility powers line 6' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 5
  printf "  'Utility powers line 7' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 6
  printf "  'Utility powers line 8' => q{%s},\n"  $ (eightUtilityPowers pontus) !! 7
  printf "  'Magic items line 1' => q{%s},\n" ""
  printf "  'Magic items line 2' => q{%s},\n" ""
  printf "  'Magic items line 3' => q{%s},\n" ""
  printf "  'Magic items line 4' => q{%s},\n" ""
  printf "  'Magic items line 5' => q{%s},\n" ""
  printf "  'Magic items line 6' => q{%s},\n" ""
  printf "  'Magic items line 7' => q{%s},\n" ""
  printf "  'Magic items line 8' => q{%s},\n" ""
  printf "  'Magic items line 9' => q{%s},\n" ""
  printf "  'Magic items line 10' => q{%s},\n" ""
  printf "  'Magic items line 11' => q{%s},\n" ""
  printf "  'Magic items line 12' => q{%s},\n" ""
  printf "  'Magic items line 13' => q{%s},\n" ""
  printf "  'Magic items line 14' => q{%s},\n" ""
  printf "  'Magic items line 15' => q{%s},\n" ""
  printf "  'Magic items line 16' => q{%s},\n" ""
  printf "  'Magic items line 17' => q{%s},\n" ""
  printf "  'Magic items line 18' => q{%s},\n" ""
  printf "  'Magic items line 19' => q{%s},\n" ""
  printf "  'Magic items line 20' => q{%s},\n" ""
  printf "  'Magic items line 21' => q{%s},\n" ""
  printf "  'Magic items line 22' => q{%s},\n" ""
  printf "  'Magic items line 23' => q{%s},\n" ""
  printf "  'Magic items line 24' => q{%s},\n" ""
  printf "  'Magic items line 25' => q{%s},\n" ""
  printf "  'Other equipment line 1' => q{%s},\n" ""
  printf "  'Other equipment line 2' => q{%s},\n" ""
  printf "  'Other equipment line 3' => q{%s},\n" ""
  printf "  'Other equipment line 4' => q{%s},\n" ""
  printf "  'Other equipment line 5' => q{%s},\n" ""
  printf "  'Other equipment line 6' => q{%s},\n" ""
  printf "  'Other equipment line 7' => q{%s},\n" ""
  printf "  'Other equipment line 8' => q{%s},\n" ""
  printf "  'Other equipment line 9' => q{%s},\n" ""
  printf "  'Other equipment line 10' => q{%s},\n" ""
  printf "  'Rituals line 1' => q{%s},\n" ""
  printf "  'Rituals line 2' => q{%s},\n" ""
  printf "  'Rituals line 3' => q{%s},\n" ""
  printf "  'Rituals line 4' => q{%s},\n" ""
  printf "  'Rituals line 5' => q{%s},\n" ""
  printf "  'Rituals line 6' => q{%s},\n" ""
  printf "  'Rituals line 7' => q{%s},\n" ""
  printf "  'Rituals line 8' => q{%s},\n" ""
  printf "  'Rituals line 9' => q{%s},\n" ""
  printf "  'Rituals line 10' => q{%s},\n" ""
  printf "  'Coins and other wealth' => q{%s},\n" ""
  printf "  'Personality traits line 1' => q{%s},\n" ""
  printf "  'Personality traits line 2' => q{%s},\n" ""
  printf "  'Personality traits line 3' => q{%s},\n" ""
  printf "  'Personality traits line 5' => q{%s},\n" ""
  printf "  'Personality traits line 4' => q{%s},\n" ""
  printf "  'Personality traits line 6' => q{%s},\n" ""
  printf "  'Personality traits line 7' => q{%s},\n" ""
  printf "  'Personality traits line 8' => q{%s},\n" ""
  printf "  'Personality traits line 9' => q{%s},\n" ""
  printf "  'Personality traits line 10' => q{%s},\n" ""
  printf "  'Personality traits line 11' => q{%s},\n" ""
  printf "  'Character background line 1' => q{%s},\n" ""
  printf "  'Character background line 2' => q{%s},\n" ""
  printf "  'Character background line 3' => q{%s},\n" ""
  printf "  'Character background line 4' => q{%s},\n" ""
  printf "  'Companions name 1' => q{%s},\n" ""
  printf "  'Companions notes 1' => q{%s},\n" ""
  printf "  'Companions name 2' => q{%s},\n" ""
  printf "  'Companions notes 2' => q{%s},\n" ""
  printf "  'Companions name 3' => q{%s},\n" ""
  printf "  'Companions notes 3' => q{%s},\n" ""
  printf "  'Companions name 4' => q{%s},\n" ""
  printf "  'Companions notes 4' => q{%s},\n" ""
  printf "  'Companions name 5' => q{%s},\n" ""
  printf "  'Companions notes 5' => q{%s},\n" ""
  printf "  'Companions name 6' => q{%s},\n" ""
  printf "  'Companions notes 6' => q{%s},\n" ""
  printf "  'Companions name 7' => q{%s},\n" ""
  printf "  'Companions notes 7' => q{%s},\n" ""
  printf "  'Companions name 8' => q{%s},\n" ""
  printf "  'Companions notes 8' => q{%s},\n" ""
  printf "  'Session and campaign notes 1' => q{%s}\n" ""
  putStrLn "};"

main = do
  printFormData
