module Form where

import Text.Printf
import Skill
import Character as C
import Pontus

-- Consider a function that if the resulting int is 0, outputs nothing, so
-- that we can write in values on the printed sheet.
printFormData c = do
  putStrLn "$fields = {"
  printf "  'Player name' => q{%s},\n" $ playerName c
  printf "  'Character name' => q{%s},\n" $ name c
  printf "  'Level' => q{%d},\n" $ level c
  printf "  'Class' => q{%s},\n" $ className c
  printf "  'Paragon path' => q{%s},\n" "" -- TODO
  printf "  'Epic destiny' => q{%s},\n" "" -- TODO
  printf "  'Total XP' => q{%d},\n" $ xp c
  printf "  'Race' => q{%s},\n" $ raceName c
  printf "  'Size' => q{%s},\n" $ size c
  printf "  'Age' => q{%d},\n" $ age c
  printf "  'Gender' => q{%s},\n" $ gender c
  printf "  'Height' => q{%s},\n" $ height c
  printf "  'Weight' => q{%s},\n" $ weight c
  printf "  'Alignment' => q{%s},\n" $ alignment c
  printf "  'Deity' => q{%s},\n" $ deity c
  printf "  'Adventuring company or other affiliation' => q{%s},\n" $ adventuringCompanyOrOtherAffiliations c
  printf "  'Dex mod to Init' => q{%d},\n" $ dexMod c
  printf "  'Half-level mod to Init' => q{%d},\n" $ halfLevel c
  printf "  'Misc. mod to Init' => q{%d},\n" $ miscModToInit c
  printf "  'Init' => q{%d},\n" $ initiative c
  printf "  'Conditional Init mods' => q{%s},\n" "" -- TODO
  printf "  'Ten plus half-level mod to AC' => q{%d},\n" $ tenPlusHalfLevel c
  printf "  'Armor or ability mod to AC' => q{%d},\n" $ armorAndAbilityModToAC c -- TODO rename field
  printf "  'Class mod to AC' => q{%d},\n" $ classModToAC c
  printf "  'Feat mod to AC' => q{%d},\n" $ featModToAC c
  printf "  'Enhancement mod to AC' => q{%d},\n" $ enhModToAC c
  printf "  'Misc. mod 1 to AC' => q{%d},\n" $ misc1ModToAC c
  printf "  'Misc. mod 2 to AC' => q{%d},\n" $ misc2ModToAC c
  printf "  'AC' => q{%d},\n" $ ac c
  printf "  'Ten plus half-level to Fortitude' => q{%d},\n" $ tenPlusHalfLevel c
  printf "  'Ability mod to Fortitude' => q{%d},\n" $ abilModToFort c
  printf "  'Class mod to Fortitude' => q{%d},\n" $ classModToFort c
  printf "  'Feat mod to Fortitude' => q{%d},\n" $ featModToFort c
  printf "  'Enhancement mod to Fortitude' => q{%d},\n" $ enhModToFort c
  printf "  'Misc. mod 1 to Fortitude' => q{%d},\n" $ misc1ModToFort c
  printf "  'Misc. mod 2 to Fortitude' => q{%d},\n" $ misc2ModToFort c
  printf "  'Fortitude' => q{%d},\n" $ fortitude c
  printf "  'Ten plus half-level to Reflex' => q{%d},\n" $ tenPlusHalfLevel c
  printf "  'Ability mod to Reflex' => q{%d},\n" $ abilModToRef c
  printf "  'Class mod to Reflex' => q{%d},\n" $ classModToRef c
  printf "  'Feat mod to Reflex' => q{%d},\n" $ featModToRef c
  printf "  'Enhancement mod to Reflex' => q{%d},\n" $ enhModToRef c
  printf "  'Misc. mod 1 to Reflex' => q{%d},\n" $ misc1ModToRef c
  printf "  'Misc. mod 2 to Reflex' => q{%d},\n" $ misc2ModToRef c
  printf "  'Reflex' => q{%d},\n" $ reflex c
  printf "  'Ten plus half-level to Will' => q{%d},\n" $ tenPlusHalfLevel c
  printf "  'Ability mod to Will' => q{%d},\n" $ abilModToWill c
  printf "  'Class mod to Will' => q{%d},\n" $ classModToWill c
  printf "  'Feat mod to Will' => q{%d},\n" $ featModToWill c
  printf "  'Enhancement mod to Will' => q{%d},\n" $ enhModToWill c
  printf "  'Misc. mod 1 to Will' => q{%d},\n" $ misc1ModToWill c
  printf "  'Misc. mod 2 to Will' => q{%d},\n" $ misc2ModToWill c
  printf "  'Will' => q{%d},\n" $ will c
  printf "  'Additional effects to spending action points' => q{%s},\n" "" -- TODO
  printf "  'Conditional mods to AC' => q{%s},\n" "" -- TODO
  printf "  'Conditional mods to Fortitude' => q{%s},\n" "" -- TODO
  printf "  'Conditional mods to Reflex' => q{%s},\n" "" -- TODO
  printf "  'Conditional mods to Will' => q{%s},\n" "" -- TODO
  printf "  'Race features - Ability score mods' => q{%s},\n" "" -- TODO
  printf "  'Race features line 2' => q{%s},\n" ""
  printf "  'Race features line 3' => q{%s},\n" ""
  printf "  'Race features line 4' => q{%s},\n" ""
  printf "  'Race features line 5' => q{%s},\n" ""
  printf "  'Race features line 6' => q{%s},\n" ""
  printf "  'Race features line 7' => q{%s},\n" ""
  printf "  'Race features line 8' => q{%s},\n" ""
  printf "  'Race features line 9' => q{%s},\n" ""
  printf "  'Str' => q{%d},\n" $ str c
  printf "  'Ability mod from Str' => q{%d},\n" $ strMod c
  printf "  'Str mod w/ level' => q{%d},\n" $ halfLevel c + strMod c -- TODO rename field
  printf "  'Con' => q{%d},\n" $ con c
  printf "  'Ability mod from Con' => q{%d},\n" $ conMod c
  printf "  'Con mod w/ level' => q{%d},\n" $ halfLevel c + conMod c -- TODO rename field
  printf "  'Dex' => q{%d},\n" $ dex c
  printf "  'Ability mod from Dex' => q{%d},\n" $ dexMod c
  printf "  'Dex mod w/ level' => q{%d},\n" $ halfLevel c + dexMod c -- TODO rename field
  printf "  'Int' => q{%d},\n" $ int c
  printf "  'Ability mod to Int' => q{%d},\n" $ intMod c
  printf "  'Int mod w/ level' => q{%d},\n" $ halfLevel c + intMod c -- TODO rename field
  printf "  'Wis' => q{%d},\n" $ wis c
  printf "  'Ability mod from Wis' => q{%d},\n" $ wisMod c
  printf "  'Wis mod w/ level' => q{%d},\n" $ halfLevel c + wisMod c -- TODO rename field
  printf "  'Cha' => q{%d},\n" $ cha c
  printf "  'Ability mod from Cha' => q{%d},\n" $ chaMod c
  printf "  'Cha mod w/ level' => q{%d},\n" $ halfLevel c + chaMod c -- TODO rename field
  printf "  'Speed' => q{%d},\n" $ speed c
  printf "  'Base Speed' => q{%d},\n" $ baseSpeed c
  printf "  'Armor Speed mod' => q{%d},\n" $ armorSpeedMod c
  printf "  'Item Speed mod' => q{%d},\n" $ itemSpeedMod c
  printf "  'Misc. Speed mod' => q{%d},\n" $ miscModToSpeed c
  printf "  'Special movement' => q{%s},\n" "" -- TODO
  printf "  'Trained in Acrobatics' => q{%d},\n" $ trainedBonus Acrobatics c
  printf "  'Trained in Arcana' => q{%d},\n" $ trainedBonus Arcana c
  printf "  'Trained in Athletics' => q{%d},\n" $ trainedBonus Athletics c
  printf "  'Trained in Bluff' => q{%d},\n" $ trainedBonus Bluff c
  printf "  'Trained in Diplomacy' => q{%d},\n" $ trainedBonus Diplomacy c
  printf "  'Trained in Dungeoneering' => q{%d},\n" $ trainedBonus Dungeoneering c
  printf "  'Trained in Endurance' => q{%d},\n" $ trainedBonus Endurance c
  printf "  'Trained in Heal' => q{%d},\n" $ trainedBonus Heal c
  printf "  'Trained in History' => q{%d},\n" $ trainedBonus History c
  printf "  'Trained in Insight' => q{%d},\n" $ trainedBonus Insight c
  printf "  'Trained in Intimidate' => q{%d},\n" $ trainedBonus Intimidate c
  printf "  'Trained in Nature' => q{%d},\n" $ trainedBonus Nature c
  printf "  'Trained in Perception' => q{%d},\n" $ trainedBonus Perception c
  printf "  'Trained in Religion' => q{%d},\n" $ trainedBonus Religion c
  printf "  'Trained in Stealth' => q{%d},\n" $ trainedBonus Stealth c
  printf "  'Trained in Streetwise' => q{%d},\n" $ trainedBonus Streetwise c
  printf "  'Trained in Thievery' => q{%d},\n" $ trainedBonus Thievery c
  printf "  'Passive Insight' => q{%d},\n" $ passiveInsight c
  printf "  'Passive Insight skill mod' => q{%d},\n" $ skill Insight c
  printf "  'Passive Perception' => q{%d},\n" $ passivePerception c
  printf "  'Passive Perception skill mod' => q{%d},\n" $ skill Perception c
  printf "  'Special senses' => q{%s},\n" "" -- TODO
  printf "  'Max HP' => q{%d},\n" $ hp c
  printf "  'Bloodied' => q{%d},\n" $ bloodied c
  printf "  'Surge value' => q{%d},\n" $ healingSurgeValue c
  printf "  'Surges per day' => q{%d},\n" $ healingSurgesPerDay c
  -- printf "  'Saving throw mods' => q{%s},\n" "" -- TODO
  -- printf "  'Resistances' => q{%s},\n" "" -- TODO
  -- printf "  'Current conditions and effects' => q{%s},\n" "" -- TODO
  -- printf "  'Class, Path, or Destiny features line 1' => q{%s},\n" "" -- TODO
  -- printf "  'Class, Path, or Destiny features line 2' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 3' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 4' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 5' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 6' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 7' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 8' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 9' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 10' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 11' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 12' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 13' => q{%s},\n" ""
  -- printf "  'Class, Path, or Destiny features line 14' => q{%s},\n" ""
  printf "  'Languages known line 1' => q{%s},\n" $ language 0 c
  printf "  'Languages known line 2' => q{%s},\n" $ language 1 c
  printf "  'Languages known line 3' => q{%s},\n" $ language 2 c
  printf "  'Ability mod plus half-level to Acrobatics' => q{%d},\n" $ skillAbilModPlusHalfLevel Acrobatics c
  printf "  'Armor mod to Acrobatics' => q{%d},\n" $ skillArmorCheckPenalty Acrobatics c
  printf "  'Misc. mod to Acrobatics' => q{%d},\n" $ miscModToSkill Acrobatics c
  printf "  'Acrobatics' => q{%d},\n" $ skill Acrobatics c
  printf "  'Misc. mod to Arcana' => q{%d},\n" $ miscModToSkill Arcana c
  printf "  'Ability mod plus half-level to Arcana' => q{%d},\n" $ skillAbilModPlusHalfLevel Arcana c
  printf "  'Arcana' => q{%d},\n" $ skill Arcana c
  printf "  'Ability mod plus half-level to Athletics' => q{%d},\n" $ skillAbilModPlusHalfLevel Athletics c
  printf "  'Armor mod to Athletics' => q{%d},\n" $ skillArmorCheckPenalty Athletics c
  printf "  'Misc. mod to Athletics' => q{%d},\n" $ miscModToSkill Athletics c
  printf "  'Athletics' => q{%d},\n" $ skill Athletics c
  printf "  'Ability mod plus half-level to Bluff' => q{%d},\n" $ skillAbilModPlusHalfLevel Bluff c
  printf "  'Misc. mod to Bluff' => q{%d},\n" $ miscModToSkill Bluff c
  printf "  'Bluff' => q{%d},\n" $ skill Bluff c
  printf "  'Ability mod plus half-level to Diplomacy' => q{%d},\n" $ skillAbilModPlusHalfLevel Diplomacy c
  printf "  'Misc. mod to Diplomacy' => q{%d},\n" $ miscModToSkill Diplomacy c
  printf "  'Diplomacy' => q{%d},\n" $ skill Diplomacy c
  printf "  'Ability mod plus half-level to Dungeoneering' => q{%d},\n" $ skillAbilModPlusHalfLevel Dungeoneering c
  printf "  'Misc. mod to Dungeoneering' => q{%d},\n" $ miscModToSkill Dungeoneering c
  printf "  'Dungeoneering' => q{%d},\n" $ skill Dungeoneering c
  printf "  'Armor mod to Endurance' => q{%d},\n" $ skillArmorCheckPenalty Endurance c
  printf "  'Misc. mod to Endurance' => q{%d},\n" $ miscModToSkill Endurance c
  printf "  'Ability mod plus half-level to Endurance' => q{%d},\n" $ skillAbilModPlusHalfLevel Endurance c
  printf "  'Endurance' => q{%d},\n" $ skill Endurance c
  printf "  'Ability mod plus half-level to Heal' => q{%d},\n" $ skillAbilModPlusHalfLevel Heal c
  printf "  'Misc. mod to Heal' => q{%d},\n" $ miscModToSkill Heal c
  printf "  'Ability mod plus half-level to History' => q{%d},\n" $ skillAbilModPlusHalfLevel History c
  printf "  'Heal' => q{%d},\n" $ skill Heal c
  printf "  'Misc. mod to History' => q{%d},\n" $ miscModToSkill History c
  printf "  'History' => q{%d},\n" $ skill History c
  printf "  'Insight' => q{%d},\n" $ skill Insight c
  printf "  'Misc. mod to Insight' => q{%d},\n" $ miscModToSkill Insight c
  printf "  'Ability mod plus half-level to Insight' => q{%d},\n" $ skillAbilModPlusHalfLevel Insight c
  printf "  'Intimidate' => q{%d},\n" $ skill Intimidate c
  printf "  'Misc. mod to Intimidate' => q{%d},\n" $ miscModToSkill Intimidate c
  printf "  'Ability mod plus half-level to Intimidate' => q{%d},\n" $ skillAbilModPlusHalfLevel Intimidate c
  printf "  'Nature' => q{%d},\n" $ skill Nature c
  printf "  'Misc. mod to Nature' => q{%d},\n" $ miscModToSkill Nature c
  printf "  'Ability mod plus half-level to Nature' => q{%d},\n" $ skillAbilModPlusHalfLevel Nature c
  printf "  'Perception' => q{%d},\n" $ skill Perception c
  printf "  'Misc. mod to Perception' => q{%d},\n" $ miscModToSkill Perception c
  printf "  'Misc. mod to Religion' => q{%d},\n" $ miscModToSkill Religion c
  printf "  'Religion' => q{%d},\n" $ skill Religion c
  printf "  'Ability mod plus half-level to Perception' => q{%d},\n" $ skillAbilModPlusHalfLevel Perception c
  printf "  'Ability mod plus half-level to Religion' => q{%d},\n" $ skillAbilModPlusHalfLevel Religion c
  printf "  'Stealth' => q{%d},\n" $ skill Stealth c
  printf "  'Armor mod to Stealth' => q{%d},\n" $ skillArmorCheckPenalty Stealth c
  printf "  'Misc. mod to Stealth' => q{%d},\n" $ miscModToSkill Stealth c
  printf "  'Ability mod plus half-level to Stealth' => q{%d},\n" $ skillAbilModPlusHalfLevel Stealth c
  printf "  'Streetwise' => q{%d},\n" $ skill Streetwise c
  printf "  'Misc. mod to Streetwise' => q{%d},\n" $ miscModToSkill Streetwise c
  printf "  'Ability mod plus half-level to Streetwise' => q{%d},\n" $ skillAbilModPlusHalfLevel Streetwise c
  printf "  'Thievery' => q{%d},\n" $ skill Thievery c
  printf "  'Armor mod to Thievery' => q{%d},\n" $ skillArmorCheckPenalty Thievery c
  printf "  'Misc. mod to Thievery' => q{%d},\n" $ miscModToSkill Thievery c
  printf "  'Ability mod plus half-level to Thievery' => q{%d},\n" $ skillAbilModPlusHalfLevel Thievery c


  printf "  'Attack workspace ability 1' => q{%s},\n" $ attack1Name c
  printf "  'Attack mod to attack 1' => q{%d},\n" $ attack1Mod c
  printf "  'Half-level to attack 1' => q{%d},\n" $ halfLevel c
  printf "  'Ability mod to attack 1' => q{%d},\n" $ attack1AbilMod c
  printf "  'Class mod to attack 1' => q{%d},\n" $ attack1ClassMod c
  printf "  'Proficiency mod to attack 1' => q{%d},\n" $ attack1ProfMod c
  printf "  'Feat mod to attack 1' => q{%d},\n" $ attack1FeatMod c
  printf "  'Enhancement mod to attack 1' => q{%d},\n" $ attack1EnhMod c
  printf "  'Misc. mod to attack 1' => q{%d},\n" $ attack1MiscMod c

  printf "  'Attack workspace ability 2' => q{%s},\n" $ attack2Name c
  printf "  'Attack mod to attack 2' => q{%d},\n" $ attack2Mod c
  printf "  'Half-level to attack 2' => q{%d},\n" $ halfLevel c
  printf "  'Ability mod to attack 2' => q{%d},\n" $ attack2AbilMod c
  printf "  'Class mod to attack 2' => q{%d},\n" $ attack2ClassMod c
  printf "  'Proficiency mod to attack 2' => q{%d},\n" $ attack2ProfMod c
  printf "  'Feat mod to attack 2' => q{%d},\n" $ attack2FeatMod c
  printf "  'Enhancement mod to attack 2' => q{%d},\n" $ attack2EnhMod c
  printf "  'Misc. mod to attack 2' => q{%d},\n" $ attack2MiscMod c

  printf "  'Damage workspace ability 1' => q{%s},\n" $ attack1Name c
  printf "  'Damage to ability 1' => q{%s},\n" $ damage1Desc c
  printf "  'Ability mod to damage to ability 1' => q{%d},\n" $ damage1AbilMod c
  printf "  'Feat mod to damage to ability 1' => q{%d},\n" $ damage1FeatMod c
  printf "  'Enhancement mod to damage to ability 1' => q{%d},\n" $ damage1EnhMod c
  printf "  'Misc. mod 1 to damage to ability 1' => q{%d},\n" $ damage1Misc1Mod c
  printf "  'Misc. mod 2 to damage to ability 1' => q{%d},\n" $ damage1Misc2Mod c

  printf "  'Damage workspace ability 2' => q{%s},\n" $ attack2Name c
  printf "  'Damage to ability 2' => q{%s},\n" $ damage2Desc c
  printf "  'Ability mod to damage to ability 2' => q{%d},\n" $ damage2AbilMod c
  printf "  'Feat mod to damage to ability 2' => q{%d},\n" $ damage2FeatMod c
  printf "  'Enhancement mod to damage to ability 2' => q{%d},\n" $ damage2EnhMod c
  printf "  'Misc. mod 1 to damage to ability 2' => q{%d},\n" $ damage2Misc1Mod c
  printf "  'Misc. mod 2 to damage to ability 2' => q{%d},\n" $ damage2Misc2Mod c

  -- printf "  'Basic attack 1 attack' => q{%d},\n" (0 :: Int)
  -- printf "  'Basic attack 1 defense' => q{%s},\n" ""
  -- printf "  'Basic attack 2 attack' => q{%s},\n" ""
  -- printf "  'Basic attack 2 defense' => q{%s},\n" ""
  -- printf "  'Basic attack 3 attack ' => q{%s},\n" ""
  -- printf "  'Basic attack 3 defense' => q{%s},\n" ""
  -- printf "  'Basic attack 4 attack ' => q{%s},\n" ""
  -- printf "  'Basic attack 4 defense' => q{%s},\n" ""
  -- printf "  'Basic attack 1 weapon or power' => q{%s},\n" ""
  -- printf "  'Basic attack 2 weapon or power' => q{%s},\n" ""
  -- printf "  'Basic attack 3 weapon or power' => q{%s},\n" ""
  -- printf "  'Basic attack 4 weapon or power' => q{%s},\n" ""
  -- printf "  'Basic attack 1 damage' => q{%s},\n" ""
  -- printf "  'Basic attack 2 damage' => q{%s},\n" ""
  -- printf "  'Basic attack 3 damage' => q{%s},\n" ""
  -- printf "  'Basic attack 4 damage' => q{%s},\n" ""
  -- printf "  'Feats line 1' => q{%s},\n" $ feat 0 c
  -- printf "  'Feats line 2' => q{%s},\n" $ feat 1 c
  -- printf "  'Feats line 3' => q{%s},\n" $ feat 2 c
  -- printf "  'Feats line 4' => q{%s},\n" $ feat 3 c
  -- printf "  'Feats line 5' => q{%s},\n" $ feat 4 c
  -- printf "  'Feats line 6' => q{%s},\n" $ feat 5 c
  -- printf "  'Feats line 7' => q{%s},\n" $ feat 6 c
  -- printf "  'Feats line 8' => q{%s},\n" $ feat 7 c
  -- printf "  'Feats line 9' => q{%s},\n" $ feat 8 c
  -- printf "  'Feats line 10' => q{%s},\n" $ feat 9 c
  -- printf "  'Feats line 11' => q{%s},\n" $ feat10 c
  -- printf "  'Feats line 12' => q{%s},\n" $ feat11 c
  -- printf "  'Feats line 13' => q{%s},\n" $ feat12 c
  -- printf "  'Feats line 14' => q{%s},\n" $ feat13 c
  -- printf "  'Feats line 15' => q{%s},\n" $ feat14 c
  -- printf "  'Feats line 16' => q{%s},\n" $ feat15 c
  -- printf "  'Feats line 17' => q{%s},\n" $ feat16 c
  -- printf "  'At-will powers line 1' => q{%s},\n" $ atWillPower 0 c
  -- printf "  'At-will powers line 2' => q{%s},\n" $ atWillPower 1 c
  -- printf "  'At-will powers line 3' => q{%s},\n" $ atWillPower 2 c
  -- printf "  'At-will powers line 4' => q{%s},\n" $ atWillPower 3 c
  -- printf "  'At-will powers line 5' => q{%s},\n" $ atWillPower 4 c
  -- printf "  'At-will powers line 6' => q{%s},\n" $ atWillPower 5 c
  -- printf "  'Daily powers line 1' => q{%s},\n" $ dailyPower 0 c
  -- printf "  'Daily powers line 2' => q{%s},\n" $ dailyPower 1 c
  -- printf "  'Daily powers line 3' => q{%s},\n" $ dailyPower 2 c
  -- printf "  'Daily powers line 4' => q{%s},\n" $ dailyPower 3 c
  -- printf "  'Daily powers line 5' => q{%s},\n" $ dailyPower 4 c
  -- printf "  'Daily powers line 6' => q{%s},\n" $ dailyPower 5 c
  -- printf "  'Encounter powers line 1' => q{%s},\n" $ encounterPower 0 c
  -- printf "  'Encounter powers line 2' => q{%s},\n" $ encounterPower 1 c
  -- printf "  'Encounter powers line 3' => q{%s},\n" $ encounterPower 2 c
  -- printf "  'Encounter powers line 4' => q{%s},\n" $ encounterPower 3 c
  -- printf "  'Encounter powers line 5' => q{%s},\n" $ encounterPower 4 c
  -- printf "  'Encounter powers line 6' => q{%s},\n" $ encounterPower 5 c
  -- printf "  'Utility powers line 1' => q{%s},\n"  $ utilityPower 0 c
  -- printf "  'Utility powers line 2' => q{%s},\n"  $ utilityPower 1 c
  -- printf "  'Utility powers line 3' => q{%s},\n"  $ utilityPower 2 c
  -- printf "  'Utility powers line 4' => q{%s},\n"  $ utilityPower 3 c
  -- printf "  'Utility powers line 5' => q{%s},\n"  $ utilityPower 4 c
  -- printf "  'Utility powers line 6' => q{%s},\n"  $ utilityPower 5 c
  -- printf "  'Utility powers line 7' => q{%s},\n"  $ utilityPower 6 c
  -- printf "  'Utility powers line 8' => q{%s},\n"  $ utilityPower 7 c
  -- printf "  'Magic items line 1' => q{%s},\n" ""
  -- printf "  'Magic items line 2' => q{%s},\n" ""
  -- printf "  'Magic items line 3' => q{%s},\n" ""
  -- printf "  'Magic items line 4' => q{%s},\n" ""
  -- printf "  'Magic items line 5' => q{%s},\n" ""
  -- printf "  'Magic items line 6' => q{%s},\n" ""
  -- printf "  'Magic items line 7' => q{%s},\n" ""
  -- printf "  'Magic items line 8' => q{%s},\n" ""
  -- printf "  'Magic items line 9' => q{%s},\n" ""
  -- printf "  'Magic items line 10' => q{%s},\n" ""
  -- printf "  'Magic items line 11' => q{%s},\n" ""
  -- printf "  'Magic items line 12' => q{%s},\n" ""
  -- printf "  'Magic items line 13' => q{%s},\n" ""
  -- printf "  'Magic items line 14' => q{%s},\n" ""
  -- printf "  'Magic items line 15' => q{%s},\n" ""
  -- printf "  'Magic items line 16' => q{%s},\n" ""
  -- printf "  'Magic items line 17' => q{%s},\n" ""
  -- printf "  'Magic items line 18' => q{%s},\n" ""
  -- printf "  'Magic items line 19' => q{%s},\n" ""
  -- printf "  'Magic items line 20' => q{%s},\n" ""
  -- printf "  'Magic items line 21' => q{%s},\n" ""
  -- printf "  'Magic items line 22' => q{%s},\n" ""
  -- printf "  'Magic items line 23' => q{%s},\n" ""
  -- printf "  'Magic items line 24' => q{%s},\n" ""
  -- printf "  'Magic items line 25' => q{%s},\n" ""
  -- printf "  'Other equipment line 1' => q{%s},\n" ""
  -- printf "  'Other equipment line 2' => q{%s},\n" ""
  -- printf "  'Other equipment line 3' => q{%s},\n" ""
  -- printf "  'Other equipment line 4' => q{%s},\n" ""
  -- printf "  'Other equipment line 5' => q{%s},\n" ""
  -- printf "  'Other equipment line 6' => q{%s},\n" ""
  -- printf "  'Other equipment line 7' => q{%s},\n" ""
  -- printf "  'Other equipment line 8' => q{%s},\n" ""
  -- printf "  'Other equipment line 9' => q{%s},\n" ""
  -- printf "  'Other equipment line 10' => q{%s},\n" ""
  -- printf "  'Rituals line 1' => q{%s},\n" ""
  -- printf "  'Rituals line 2' => q{%s},\n" ""
  -- printf "  'Rituals line 3' => q{%s},\n" ""
  -- printf "  'Rituals line 4' => q{%s},\n" ""
  -- printf "  'Rituals line 5' => q{%s},\n" ""
  -- printf "  'Rituals line 6' => q{%s},\n" ""
  -- printf "  'Rituals line 7' => q{%s},\n" ""
  -- printf "  'Rituals line 8' => q{%s},\n" ""
  -- printf "  'Rituals line 9' => q{%s},\n" ""
  -- printf "  'Rituals line 10' => q{%s},\n" ""
  -- printf "  'Coins and other wealth' => q{%s},\n" ""
  -- printf "  'Personality traits line 1' => q{%s},\n" ""
  -- printf "  'Personality traits line 2' => q{%s},\n" ""
  -- printf "  'Personality traits line 3' => q{%s},\n" ""
  -- printf "  'Personality traits line 5' => q{%s},\n" ""
  -- printf "  'Personality traits line 4' => q{%s},\n" ""
  -- printf "  'Personality traits line 6' => q{%s},\n" ""
  -- printf "  'Personality traits line 7' => q{%s},\n" ""
  -- printf "  'Personality traits line 8' => q{%s},\n" ""
  -- printf "  'Personality traits line 9' => q{%s},\n" ""
  -- printf "  'Personality traits line 10' => q{%s},\n" ""
  -- printf "  'Personality traits line 11' => q{%s},\n" ""
  -- printf "  'Character background line 1' => q{%s},\n" ""
  -- printf "  'Character background line 2' => q{%s},\n" ""
  -- printf "  'Character background line 3' => q{%s},\n" ""
  -- printf "  'Character background line 4' => q{%s},\n" ""
  -- printf "  'Companions name 1' => q{%s},\n" ""
  -- printf "  'Companions notes 1' => q{%s},\n" ""
  -- printf "  'Companions name 2' => q{%s},\n" ""
  -- printf "  'Companions notes 2' => q{%s},\n" ""
  -- printf "  'Companions name 3' => q{%s},\n" ""
  -- printf "  'Companions notes 3' => q{%s},\n" ""
  -- printf "  'Companions name 4' => q{%s},\n" ""
  -- printf "  'Companions notes 4' => q{%s},\n" ""
  -- printf "  'Companions name 5' => q{%s},\n" ""
  -- printf "  'Companions notes 5' => q{%s},\n" ""
  -- printf "  'Companions name 6' => q{%s},\n" ""
  -- printf "  'Companions notes 6' => q{%s},\n" ""
  -- printf "  'Companions name 7' => q{%s},\n" ""
  -- printf "  'Companions notes 7' => q{%s},\n" ""
  -- printf "  'Companions name 8' => q{%s},\n" ""
  -- printf "  'Companions notes 8' => q{%s},\n" ""
  -- printf "  'Session and campaign notes 1' => q{%s}\n" ""
  putStrLn "};"

main = do
  printFormData pontus
